function [BW] = segmentImage5(X, erode, sens)
% Accept three input parameters: X (input image), erode (radius of the erosion operation), sens (sensitivity of the adaptive threshold)
% The output BW is the segmented binary image.
% segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 03-Jul-2019
%----------------------------------------------------

% Threshold image - adaptive threshold
BW = imbinarize(X, 'adaptive', 'Sensitivity', sens, 'ForegroundPolarity', 'dark');
% The imbinarize function uses an adaptive thresholding method to convert the image X into a binary image BW. The parameter 'Sensitivity', sens sets the sensitivity,
% and 'ForegroundPolarity', 'dark' specifies that the foreground is dark (i.e., segmenting the darker areas). 'bright': foreground pixels are brighter than background pixels.

se = strel('rectangle',[1 3]);
% se = strel('disk',1);
BW = imdilate(BW, se);
BW = imerode(BW, se);
BW = bwareaopen(BW, 100); 

end

